name: remote ssh command
on:
  push:
    branches: 
    - main

jobs:
  push_to_registry_API:
    name: Push Docker API image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: grsantosv/mlops-api
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./API/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  push_to_registry_DATA:
    name: Push Docker DATA image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: grsantosv/mlops-data
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./DATA/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  copy_docker_compose:
    name: copy docker-compose to server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: executing remote ssh commands using privatekey
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CONNECTKEY }}
        port: ${{ secrets.PORT }}
        source: "docker-compose.yml"
        target: "./"
  connect:
    name: connect to server and run
    needs: 
      - push_to_registry_API
      - push_to_registry_DATA
      - copy_docker_compose
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using privatekey
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CONNECTKEY }}
        port: ${{ secrets.PORT }}
        script: |
                true || docker stop $(docker ps -a -q) && \
                yes | docker system prune -a && \
                mkdir -p api_data && \
                mkdir -p api_model && \
                mkdir -p api_log_file && \
                docker-compose up -d